### ISSUE TITLE
"as" can't be used as a variable identifier and same time error doesn't say whether its a keyword

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1867]
Trying to run following code[1] and its gives error [2]

[1]
import ballerina.lang.system;

function main(string[] args){

  // int as;
  string[] as = ["30","10","1","3","0","4","6","2"];
  // as =["a","b"];

 system:println(as[0]);

 }

[2]
asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina run /home/asankav/myarea/bal/Test/blocktest.bal 
blocktest.bal:6:11: mismatched input 'as'. Expecting one of Identifier

**Comment by SupunS** [comment]
None of the keywords can be used as identifiers (variable names, function names, etc..). Using 'as' is throwing an error, because it is also a keyword in ballerina (used in import statements), which is the correct behavior.
The related error is thrown from the parser itself, so it has no context about the reason. At the parser level, it can only tell that the token expected is different from what is found. We can see the same beahvior in other languages as well like java and etc.
