### ISSUE TITLE
Messages are getting removed from the queue when there are errors in the program

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2113]
1. In the JMS server side, try to retrieve an integer value from the following method
`system:println("Message received - " + messages:getStringValue(m,"states"));`
Related to : https://github.com/ballerinalang/ballerina/issues/2112
2. This will throw an error
3. Check the queue

Issue
The messages will be removed even without acknowledging

**Comment by Megala21** [comment]
@dilinisg - When there is a error, we call the jms session.recover(). As per the jms API, http://docs.oracle.com/javaee/7/api/javax/jms/Session.html#recover--, it should try to re-deliver the message. But seems like MB is adding it to the dead-letter channel. In ActiveMq, it tries to re-deliver the message again for certain number of times. @pamod @ramith - Can you comment on this behavior please?

**Comment by a5anka** [comment]
The correct behavior in MB also should be moving the message to DLC after exceeding the maximum redelivery count (which is 10 by default).

**Comment by Megala21** [comment]
This issue is not there in MB 3.2 Alpha.

**Comment by pamod** [comment]
@Megala21 JMS recovery() would result it rejecting all un-acked messages for the given session. 

In the implementation of MB and as per the AMQP spec. The messages would be sent from the broker to the client as a batch. i.e if there're 10 messages in the queue all the 10 messages will be sent as once to the client as a batch. AMQP defines this as a mechanism to improve performance. 

As a result all the messages sent to the client, despite it being received by the high-level API or not would be rejected resulting in all the messages in the batch to move to the DLC after the number of retries are breached. 

Unfortunately JMS doesn't define a way to recover/rollback individual messages. We're discussing alternative ways to identify ways to distinguish the messages which are received by the API and the once which have not. So that we could maintain the retry count only for the messages which are received, so that the messages which are actually received by the API are sent to the DLC. 

Will update  https://wso2.org/jira/browse/MB-1896 with the progress.

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerinalang/connector-jms/issues/22 to track this
