### ISSUE TITLE
Change error message when browser calls /favicon.ico 

### ISSUE THREAD

**Issue by lahirus** [ballerinalang/ballerina#2289]
Saw in "passthroughService" sample when invoked following from browser,
http://localhost:9090/nyseStock

"error in ballerina program: no service found to handle incoming request recieved to : /favicon.ico"

Since this is not a problem with server or Ballerina, we need to point the correct problem.

**Comment by pubudu91** [comment]
Tried this out in v0.95.4-SNAPSHOT and could not reproduce the issue.

**Comment by pubudu91** [comment]
Correction: It seems newer browsers doesn't send the request for favicon automatically. Tested on an older browser and got he following error message on the console:
`no matching service found for path : /favicon.ico`

This error message is correct since there really isn't a service named `favicon.ico` in the passthrough sample service. If a user feels this needs to be handled, then the user should add a service to handle favicons.
