### ISSUE TITLE
[Transform] Cannot use native functions inside transform block

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2510]
eg:

```
    transform {
        e.fname = strings:toUpperCase(getFirstName(p.first_name));  //works fine

        message msg = {};
        messages:setStringPayload(msg, "ddddd"); //does not work
        e.message = msg;

    }
```

**Comment by maheeka** [comment]
We do not allow functions without return types to be used in transform blocks at the moment. The idea is the transformed content based on input variables must be assigned to an output variable. This is a function which modifies arguments directly without a return, which is a deviation from the planned behavior. Will check on the possibility of supporting such situations and get back.

**Comment by maheeka** [comment]
Due to the limitation in visually representing functions that modify passed references (without returns), we are not allowing this scenario in the transform statement. As an alternative, you can use a custom function that wraps `messages:setStringPayload()` function and returns a `message`, which can then be used in the transform. 

Closing this issue based on the above description.
