### ISSUE TITLE
[Transaction] Allow sequential access for same Parameter array for multiple insert statements

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2624]
**Current Behaviour** 
```
sql:Parameter[] paramsPerson = [paraId, paraLName, paraFName, paraAge];
                sql:Parameter[] paramsPerson_2 = [paraId, paraLName, paraFName];
                sql:ClientConnector.update (connectorInstance, "insert into persons (id, lastname, firstname, age) values (?, ?, ?, ?)", paramsPerson);
                sql:ClientConnector.update (connectorInstance, "insert into personsinlanka (personid, lastname, firstname) values (?, ?, ?)", paramsPerson_2);
```

**Expected improvement**

```
sql:Parameter[] paramsPerson = [paraId, paraLName, paraFName, paraAge];
                      sql:ClientConnector.update (connectorInstance, "insert into persons (id, lastname, firstname, age) values (?, ?, ?, ?)", paramsPerson);
                sql:ClientConnector.update (connectorInstance, "insert into personsinlanka (personid, lastname, firstname) values (?, ?, ?)", paramsPerson);
```

With the above improvement, the developer gets the capability to use the same Parameter array in multiple statements sequentially. Hence the need to define Parameter array per insert statement will be ommited.

**Comment by anupama-pathirage** [comment]
Using the same parameter array across multiple actions has  several drawbacks.

- Code become less understandable since same parameter array is used for different actions even though some array elements are not used.

- Currently the query string is not analyzed. But with the suggested change we need to count number of "?" symbols in a given query which is not a good design approach.
