### ISSUE TITLE
In Client Connector Action it is mandatory to have a message as a parameter even if it is a GET

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerinalang/ballerina#2663]
When we trying to perform a action like GET on a client connector it is mandatory to have three parameters. Otherwise this[1] error appear. 

![image](https://user-images.githubusercontent.com/9109762/27468305-c00c53c0-5806-11e7-93fe-e4f726457795.png)

Final parameter is of type message. This is ideal for a action like POST as there can be a payload that need to be sent. But it is not mandatory for a action like GET as there is no payload to be sent and might not have user set headers. So when developing we have to provide a empty variable of type message to use the GET action.

Is there a reason for message parameter to be mandatory in connector actions? 

Can we add like a default parameter if user doesn't provide a parameter value, like in javascript[1]? 

ex:-
```js
function setBackgroundColor(element, color = 'rosybrown') {
  element.style.backgroundColor = color;
}
```

[1]. https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Default_parameters

**Comment by maheeka** [comment]
@shafreenAnfar , @sameera-jayasoma 

When we are using a function to invoke a HTTP endpoint, with this approach, it becomes mandatory to define `message m = {}` before doing the GET call. In resources, we do not have an issue because we already have a `message m` object in the scope. 

Following works with an empty new message.
```
message m = {};
m = http:ClientConnector.get(endpoint1, "/");
```
Hence, there is must be no reference to any context from m in the get method and should be able to remove. 

Can we remove this parameter for the next release?

**Comment by shafreenAnfar** [comment]
Hi All,

This is as per the current design. Mainly influenced by the constraint of not letting function over-loading in ballerina. However, we are in the process of refactoring both server and client connector and as a part of it this is also considered. Following is the issue created for this. 

https://github.com/ballerinalang/ballerina/issues/4183

Hence, I will be closing this issue as it will be covered by the above issue.
