### ISSUE TITLE
[DateTime] Invalid time zone format when the time is converted using the format method

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2785]
"Invalid time zone format: .03+0530" error is thrown when the format is given like below.

string datetime = time:format(timeStruct, "yyyy-MM-dd'T'HH:mm:ss.SSX");

**Comment by anupama-pathirage** [comment]
The given error occurs not when formatting, but when inserting the formatted data into timestamp column via ballerina SQL connector. Currently ballerina sql parameters accepts either int or ISO8601 formatted strings only. In ISO 8601, the timezone format is  +hh:mm or -hh:mm. But the symbol 'X' in above format string produce timezone with no semicolon and hence giving the format error when inserting. This happens since java formatter omits the colon when formatting the zone.

As a workaround we can use time:toString which converts time struct directly into ISO formatted string.
