### ISSUE TITLE
Structs with inner structs cannot be assigned values without initializing inner struct

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/ballerina#2873]
Consider the following example : 
```
struct Person {
    string first_name;
    string last_name;
    int age;
    Address address;
}

struct Address {
    string number;
    string street;
    string city;
    PhoneNumber phoneNumber;
}

struct PhoneNumber {
    string areaCode;
    string phoneNumber;
}

struct Employee {
    string name;
    string location;
    Address address;
}

function main (string[] args) {
    Person p = {first_name: "John",last_name: "Doe",age: 30, address : {phoneNumber:{}}};
    Employee e = {address : {phoneNumber:{}}};

    transform {
        e.name = p.first_name;
        e.location = p.address.city;
        e.address.number = p.address.number;
        e.address.street = strings:toUpperCase(p.address.street);
        e.address.phoneNumber.areaCode = p.address.city;
    }
}
```

Please note that in order to run the above sample, Employee e has to have it's inner structs initialized as `Employee e = {address : {phoneNumber:{}}};`. If initialized as `Employee e = {}`, `e.address.number` and `e.address.phoneNumber.areaCode`  cannot be accessed with following error.

```
error: ballerina.lang.errors:NullReferenceError
	at main(4_complex_types.bal:35)
```

**Comment by SupunS** [comment]
This is the expected behaviour. Every field in a struct takes the default value of their respective type, when initialized with the empty initializer.
i.e.: if the fields are value-type fields, then they will take the following values:
- string --> empty string ("")
- int/float --> zero (0)
- boolean --> false

 If the fields are refrence-type fields, then they will take null, which is the default value for ref-type.
