### ISSUE TITLE
Line number issue in redeclared symbol error message

### ISSUE THREAD

**Issue by Shan1024** [ballerinalang/ballerina#3069]
```
import ballerina.net.http;
import ballerina.lang.messages;

@http:configuration {basePath:"/hello"}
service<http> HelloService {

    @http:GET {}
    @http:Path {value:"/"}
    resource sayHello (message m) {
        message response = {};
        messages:setStringPayload(response, "Hello World !!!");
        reply response;
    }
}

function HelloService () {

}
```
When we try to run the service from the above sample, we get the following message.

```
test.bal:5: redeclared symbol 'HelloService'
```
But actually the function HelloService defined in the line number 16 is the redeclaration because it comes later in the file.

**Comment by chintana** [comment]
I think this is by design. Currently Ballerina process functions first (where ever those are defined) and then services. See here line 270 and 271 [SemanticAnalyzer.java](https://github.com/ballerinalang/ballerina/blob/00cc79851f0b2411e2f9b17f5e1824d0ee1a4f44/modules/ballerina-core/src/main/java/org/ballerinalang/util/semantics/SemanticAnalyzer.java#L270-L271).

If you define the function before the service, it'll identify the line number of the service and say there's a redeclaration at the service level. Which is correct.

```
import ballerina.net.http;
import ballerina.lang.messages;

function HelloService () {

}

@http:configuration {basePath:"/hello"}
service<http> HelloService {

    @http:GET {}
    @http:Path {value:"/"}
    resource sayHello (message m) {
        message response = {};
        messages:setStringPayload(response, "Hello World !!!");
        reply response;
    }
}
```

Will give you'

```
test.bal:9: redeclared symbol 'HelloService'
```

**Comment by SupunS** [comment]
Yes @chintana is correct. Functions are visited first, since they can be used within the services.
