### ISSUE TITLE
When @ sign is used in the path, even after url-encoding the Ballerina service failed to invoked

### ISSUE THREAD

**Issue by muthulee** [ballerinalang/ballerina#3083]
import ballerina.lang.messages;
import ballerina.net.http;

@http:config {basePath:"/hello"}
service<http> helloWorld {

    @http:GET{}
    @http:Path {value:"/{myName}/occupation"}
    resource sayHello (message m, @http:PathParam {value:"myName"} string name) {
        message response = {};
        messages:setStringPayload(response, "Hello, " + name);
        reply response;
    
    }
    
}

**Comment by shafreenAnfar** [comment]
Here the problem is @ character. This is a special character according to URI spec. Therefore, URI encoding and decoding rules applies for this character. Hence, you need to add + sign before, path param as in the below example. 

import ballerina.net.http;
import ballerina.lang.messages;

@http:configuration {basePath:"/hello"}
service<http> HelloService {

    @http:GET {}
    @http:Path {value:"/{+myName}/occupation"}
    resource sayHello (message m, @http:PathParam {value:"myName"} string email) {
        message response = {};
        messages:setStringPayload(response, "Hello World !!!" + email);
        reply response;
    }
}
