### ISSUE TITLE
[HTTP] Allow the user to control Chunking

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/ballerina#3126]
Add a property to Enable or Disable chunking. IMO default behavior should be if the Content-Length header is present chunking should be disabled. At the same time, the user should be able to control Chunking. Following are some use cases.

Request Path
**Client** --- not chunked --> **Ballerina** --- chunked---> **BackEnd**
**Client** --- chunked --> **Ballerina** --- not chunked ---> **BackEnd**

Response Path
**BackEnd** --- not chunked --> **Ballerina** --- chunked---> **Client**
**BackEnd** --- chunked --> **Ballerina** --- not chunked ---> **Client**

**Comment by chamil321** [comment]
Repeated issues #1738

**Comment by shafreenAnfar** [comment]
Hi Yassas,

I do understand the fact that this need to be implemented on the client-connector side and we have done so. Under client connector options now we can specify if we need to enable or disable chunking. 

But I don't understand why we need it on the server-connector side. Because the request is originated from the client and based on request we decide how to respond. For instance, if the request is sent with Content-Length we send the back response with Content-Length. Likewise if the request is sent with Transfer-Encoding, we sent back the response with Transfer-Encoding. 

Hence, I don't see the need for configuring it on the server-connector side.
