### ISSUE TITLE
How can we change the default logging location 

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/ballerina#3529]
This document https://ballerinalang.org/docs/by-example/log-api specifies that the default logs are logged in the console. So how can we change this default behavior?

**Comment by pubudu91** [comment]
At the moment, the way to change the default behaviour is by making the necessary configurations through `<BALLERINA_HOME>/bre/conf/logging.properties` file. But this will be removed in near future since this is a config file for JDK logging and since we will be introducing a Ballerina config file and Ballerina specific log configurations through that config file.

**Comment by pubudu91** [comment]
Ballerina user level logs will be logged to the console. If there is a need to get these to a file, the user will have to redirect the logs to a file.

**Comment by anupama-pathirage** [comment]
As per the above comment, I am closing this issue.
