### ISSUE TITLE
[Documentation] No docs on how to define and use xml arrays

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#3557]
No docs on how to define and use xml arrays. But json has.

**Comment by SupunS** [comment]
Creating arrays from ballerina types is described in [1] and [2]. Same applies for XML as well.
However, there's a separate sample for JSON since JSON is a special case, where a JSON itself can be an array.

[1] https://ballerinalang.org/docs/by-example/arrays
[2] https://ballerinalang.org/docs/by-example/array-of-arrays
