### ISSUE TITLE
Native error and TypeCaseError has two different text formats

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#3679]
Is there any reason for "error" to be all simple and "TypeCaseError" has a different format. The question arose because both are supported by Ballerina as native and shouldn't keywords all be in the same template?

**Comment by hasithaa** [comment]
@erandidesilva. This issue was discussed multiple times, and the conclusion was to go with the current design. 
The rule we followed:
the 'error' is a built-in type hence it is worded as other types. (int, xml, json etc). TypeCaseError is a struct and it has multiple words. As a convention, we use CamelCase to represent such structs.
