### ISSUE TITLE
Typo in errors

### ISSUE THREAD

**Issue by manuranga** [ballerinalang/ballerina#3680]
Typo in https://github.com/ballerinalang/ballerina/search?utf8=%E2%9C%93&q=extraneous&type=
should be `erroneous`.

**Comment by hasithaa** [comment]
@manuranga. I think word extraneous is correct in this context.  
(extraneous means "irrelevant or unrelated to the subject being dealt with. " ) thoughts ?

**Comment by manuranga** [comment]
Do we ship a dictionary with the product :-p

**Comment by manuranga** [comment]
As someone who does spelling mistakes often, my guess is, it's a spell auto corrector fix. Hard to believe someone intentionally wrote obscure English word to explain a simple error.

**Comment by SupunS** [comment]
@manuranga, 'extraneous' is not actually a typo or an auto-corrected word, but is intentional. This term is coming from the lexer context. It hints that there's an additional token than what is expected (the opposite of the missing token error). ANTLR also use the same term in their default/in-built error strategies. :)
