### ISSUE TITLE
Error in getting keys from a map with reference variable modifications

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/ballerina#3959]
Observing the following error : 
```
error: error, message: org.ballerinalang.model.values.BMap cannot be cast to org.ballerinalang.model.values.BNewArray
	at .:main(/Users/maheeka/testmapkeys.bal:16)
```
Source : 

```
function main(string[] args) {
    
    map parameters = {};
    parameters["message"]= "hello Ballerina!"; 
    parameters["user"]= "Admin"; 
    
   string status = "Hello status from Ballerina";
    parameters["status"]= status; 
    string urlParams= "status=" + status;

    string[] parameterKeys = parameters.keys();
    //println(parameterKeys);   
    string[] sortedParameters = parameterKeys.sort(); 
    int index = 0;
    while (index < lengthof sortedParameters){
        string key =  sortedParameters[index]; 
        var value, _= (string) parameters[key]; 
        println(key + "=" + value); 
        index= index + 1; 
    } 
}
```

Uncommenting the `//println(parameterKeys); ` will resolve the issue.

The error causing source is :
```
    string status = "Hello status from Ballerina";
    parameters["status"]= status; 
    string urlParams= "status=" + status;
```
The error occurs in `lengthof sortedParameters`
Without the above, the scenario works as expected.

**Comment by lankavitharana** [comment]
U have to use "sort" function in "ballerina.util.arrays" package, array functions are not binded to the type. 
Anyway this needs to be fixed, either we have to bind array functions to the type or we should fail this at semantic phase. Will check and update

**Comment by djkevincr** [comment]
+1, code has reached execution of 'lengthof' instruction which is wrong, needs to be failed at semantic phase when analyzing statement string[] sortedParameters = parameterKeys.sort(). Because of that, when code generation of lengthof instruction happens,  map parameters's reference index is somehow ended up in used as reference index for lengthof calculation, hence cast class exception. Anyway use of sort() native function solved me the issue.
