### ISSUE TITLE
http:Request returns an unwanted boolean with the header string

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/ballerina#3961]
Both boolean and string return says header value

<img width="727" alt="image" src="https://user-images.githubusercontent.com/1029806/32493245-0feb6fa6-c3b5-11e7-836e-274fcdd45fff.png">

**Comment by pubudu91** [comment]
Unfortunately, this is a design limitation in the current doc system. Since the return params are unnamed, there is no way to map them to the relevant doc annotation. So it just keeps defaulting to the first return param doc annotation for all the return params.

**Comment by pubudu91** [comment]
Re: the title of this issue, the boolean is not unwanted. It is in place so that the user can distinguish between empty header values and non-existent header values. Since strings in Ballerina aren't nullable, an empty string is returned for both empty headers and non-existent headers. To be able to distinguish between the two cases, a boolean is returned along with the header. True is returned is the header is present. Users can either use this value or disregard it at their discretion.

**Comment by anupama-pathirage** [comment]
This is an issue with docerina. Hence opened https://github.com/ballerinalang/docerina/issues/132 to track this.
