### ISSUE TITLE
If a different cookie is sent before the BSESSIONID it's not detected

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/ballerina#4222]
Tried sending the following, which failed. Ballerina didn't detect the BSESSIONID.

curl -v http://localhost:9090/api/session -H "Cookie: A=5; BSESSIONID=FE9716F20E97667283630082D4BA2EE6;

**Comment by BuddhiWathsala** [comment]
I faced the same issue. I need to add more to this. I try to resolve this issue using following steps.
1. Extract the Cookie header
2. Change it with removing unnecessary values like `A=5;`
3. Then reassign the correct Cookie header.

Then it gives another error because when there is a space in Cookie header like `Cookie:<space>BSESSIONID=FE9716F20E97667283630082D4BA2EE6` 

So when we reassign header we've to use `trim()` function as well.
