### ISSUE TITLE
Cannot create a database through Ballerina

### ISSUE THREAD

**Issue by pranavan15** [ballerinalang/ballerina#4470]
**Description:**
In the current implementation of Ballerina `sql:ClientConnector` is tightly coupled with the database name. This limits users from creating a database through Ballerina.

**Suggested Labels (optional):**
Type/Improvement

**Comment by anupama-pathirage** [comment]
You can create a database in using current ballerina SQL Connector as follows. When creating a new database we need connect by directly providing the DB URL instead of providing the DB name. The database name in the sql:ClientConnector is given to ease the common use cases so that user don't have to give the url explicitly.

```ballerina
function main (string[] args) {
    endpoint<sql:ClientConnector> testDB {
        create sql:ClientConnector(sql:DB.GENERIC, "", 0, "", "root", "root", {url:"jdbc:mysql://localhost:3306/"});
    }

    int ret = testDB.update("CREATE DATABASE MYTESTDB", null);
    println(ret);
}
```
